FROM centos:7

# 设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 安装编译工具和依赖
RUN yum -y update && yum -y install \
    gcc \
    gcc-c++ \
    make \
    cmake \
    mysql-devel \
    epel-release \
    && yum clean all

# 设置工作目录
WORKDIR /app

# 复制源代码和配置文件
COPY . /app/

# 编译安装hiredis
RUN cd third_party/hiredis && \
    make && \
    make install && \
    ldconfig

# 编译项目
RUN make server

# 暴露服务端口
EXPOSE 8080

# 启动服务
CMD ["./bin/server"]