version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  redis:
    image: redis:6.2.12
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app_network

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    dns:
      - 8.8.8.8
      - 114.114.114.114
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: